# Generated by Django 3.2.8 on 2022-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('quanty', models.TextField()),
                ('price', models.TextField()),
                ('tax', models.TextField()),
                ('initial_inventory', models.TextField()),
                ('exhausted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('quanty', models.TextField()),
                ('price', models.TextField()),
                ('tax', models.TextField()),
                ('client', models.TextField()),
                ('empleoyee', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
