# Generated by Django 3.2.8 on 2022-03-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_token'),
        ('inventory', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.TextField(unique=True),
        ),
    ]
