# Generated by Django 3.2.8 on 2022-03-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.TextField(default=''),
        ),
    ]
