# Generated by Django 3.2.8 on 2022-03-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_identification_number'),
        ('company', '0001_initial'),
        ('data', '0002_payment_form_payment_method_type_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('prefix', models.TextField()),
                ('code', models.TextField()),
                ('quanty', models.TextField()),
                ('description', models.TextField()),
                ('price', models.TextField()),
                ('tax', models.TextField()),
                ('notes', models.TextField()),
                ('date', models.TextField()),
                ('ipo', models.TextField()),
                ('discount', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Form_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.TextField()),
                ('duration_measure', models.TextField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('payment_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.payment_form')),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.payment_method')),
            ],
        ),
    ]
