# Generated by Django 3.2.8 on 2022-03-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20220323_1606'),
        ('data', '0003_payroll_type_document_identification_type_contract_type_worker'),
        ('empleoyee', '0002_delete_empleoyee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleoyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentIdentification', models.TextField(unique=True)),
                ('firstname', models.TextField()),
                ('surname', models.TextField()),
                ('second_surname', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('salary', models.TextField()),
                ('user', models.TextField()),
                ('passwd', models.TextField()),
                ('block', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('payroll_type_document_identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.payroll_type_document_identification')),
                ('type_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_contract')),
                ('type_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_worker')),
            ],
        ),
    ]
